# Site settings
title: The Opportunity Project
description: USWDS makes it easier to build accessible, mobile-friendly government websites for the American public.
google_analytics_ua: UA-48605964-43
meta:
  og:image: /img/uswds-logo/lg-black.png

# this ensure that posts with future dates are published
future: true

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
    - "_components/form-controls/*"
    - "_components/form-templates/*"

jekyll_get:
  - data: releases
    json: "https://api.github.com/repos/uswds/uswds/releases"

collections:
  components:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: components
    values:
      layout: component
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css

env: dev
