topics:
  - Addressing
  - Census
  - Disasters
  - Discovery
  - Economic Development
  - Education
  - Employment
  - Entrepreneurship
  - Environment
  - Grants
  - Health
  - Housing
  - Opioids
  - Refugees
  - Rural
  - Transportation
  - Veterans
years:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
agencies:
  - label: Census Bureau
  - label: Environmental Protection Agency
  - label: Department of Agriculture
  - label: Department of Education
  - label: Department of Health and Human Services
  - label: Department of Homeland Security
  - label: Department of Housing and Urban Development
  - label: Department of Labor
  - label: Department of State
  - label: Department of the Treasury
  - label: Department of Transportation
  - label: Department of Veterans Affairs
  - label: Economic Development Administration
  - label: Federal Emergency Management Agency
  - label: Forest Service
  - label: Office of Management and Budget
  - label: Office of the U.S. Surgeon General
  - label: The Wilson Center
  - label: USA for UNHCR
    value: USA for United Nations High Commissioner for Refugees
  - label: White House Council of Economic Advisors
  - label: White House Office of Science and Technology Policy
