topics:
  - Earth
  - 2020 Census
  - Workforce
  - Geocohort
  - '2018 - ED DOL OMB/Treasury'
  - '2017 - Census OMB/Treasury'
  - '2017 - ED HUD VA'
  - Agency
  - '2016 - Sprint 1'
years:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
agencies:
  - Department of Veterans Affairs
  - Department of Education
  - Census Bureau
  - Office of Management and Budget
  - Department of the Treasury
  - Department of Labor
  - Department of Housing and Urban Development
  - Department of Transportation
  - Department of Agriculture
  - Office of the U.S. Surgeon General
  - Department of Health and Human Services
  - Department of Homeland Security
  - Federal Emergency Management Agency
  - White House Office of Science and Technology Policy
  - Forest Service
  - White House Council of Economic Advisors
  - Economic Development Administration
